### PR TITLE
[FIX] PluginManifest difference to obsidian

### LINKED ISSUE #36: [Bug] the PluginManifest don't match the PluginManifest from obsidian
obsidian-typings
```
interface PluginManifest {
    /**
     * Name of the author of the plugin
     */
    author: string;
    /**
     * URL to the author's website
     */
    authorUrl?: string;
    /**
     * Description of the plugin's functionality
     */
    description: string;
    /**
     * Storage location of the plugin relative to the vault root
     */
    dir: string;
    /**
     * URL for funding the author
     */
    fundingUrl?: string;
    /**
     * Unique identifier of the plugin
     */
    id: string;
    /**
     * Whether the plugin is designed for desktop use only
     */
    isDesktopOnly: boolean;
    /**
     * Minimum Obsidian version compatible with the plugin
     */
    minAppVersion: string;
    /**
     * Name of the plugin
     */
    name: string;
    /**
     * Version of the plugin
     */
    version: string;
}
```

obsidian
```
export interface PluginManifest {
    /**
     * Vault path to the plugin folder in the config directory.
     * @public
     */
    dir?: string;
    /**
     * The plugin ID.
     * @public
     */
    id: string;
    /**
     * The display name.
     * @public
     */
    name: string;
    /**
     * The author's name.
     * @public
     */
    author: string;
    /**
     * The current version, using {@link https://semver.org/ Semantic Versioning}.
     * @public
     */
    version: string;
    /**
     * The minimum required Obsidian version to run this plugin.
     * @public
     */
    minAppVersion: string;
    /**
     * A description of the plugin.
     * @public
     */
    description: string;
    /**
     * A URL to the author's website.
     * @public
     */
    authorUrl?: string;

    /**
     * Whether the plugin can be used only on desktop.
     * @public
     */
    isDesktopOnly?: boolean;
}
```

``dir`` and ``isDesktopOnly`` is in obsidian optional

### PR DESCRIPTION
**Pull request by 4Source**
Changed PluginManifest.dir and PluginManifest.isDesktopOnly to be optional like in obsidian.

Fixes #36

### CODE REVIEW

**Comment by Fevol** [comment]
Sorry for the wait, thanks for the PR!

**Comment by 4Source** [comment]
Is this now included in Installation type Automatic type extending (recommended)?

**Comment by Fevol** [comment]
In a bit, I am currently working on posting the new release!

**Comment by 4Source** [comment]
No pressure just wanted to ask

**Comment by Fevol** [comment]
New NPM version should now be out (if everything went well)

**Pull request merged**
