### PR TITLE
Fix spelling mistakes

### PR DESCRIPTION
**Pull request by mnaoumov**

### CODE REVIEW

**Comment by mnaoumov** [comment]
Merge after #55

**Comment by Fevol** [comment]
Thanks! Is the `vscode` Hunspell settings file necessary/useful?

**Comment by mnaoumov** [comment]
@Fevol settings file is not necessary but it is useful as it will help to distinguish possible future spelling mistakes from the whitelisted ones that spell checker didn't know

**Comment by Fevol** [comment]
As I am personally using Webstorm, the config wouldn't be very useful for me. If it's alright, I think it should be an user-config, rather than a part of the repository.

**Comment by mnaoumov** [comment]
@Fevol I can modify all of my PRs removing this config if you don't want to keep it in the repository.

I understand that Webstorm can't take advantage of the config directly but I thought it's a good idea to list all the spell checker exception whitelist words in the plain text format, so you can take those words and add to your tool of interest. 

We can move them into some tool agnostic file like `spellcheck-exceptions.txt`, if you choose to. 

Please let me know how do you want to proceed.

**Comment by Fevol** [comment]
I did some digging and it seems like Jetbrains IDE's primarily make use of `.dic` files -- setting those up properly seems to be too much of a hassle (both in terms of integrating them into the IDE configuration, and actually creating and updating them), so I'm fine with just merging the PR as-is.

**Pull request merged**
